//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScriptConfigRef) DeepCopyInto(out *ScriptConfigRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScriptConfigRef.
func (in *ScriptConfigRef) DeepCopy() *ScriptConfigRef {
	if in == nil {
		return nil
	}
	out := new(ScriptConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StarlarkInput) DeepCopyInto(out *StarlarkInput) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StarlarkInput.
func (in *StarlarkInput) DeepCopy() *StarlarkInput {
	if in == nil {
		return nil
	}
	out := new(StarlarkInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StarlarkInput) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StarlarkInputSpec) DeepCopyInto(out *StarlarkInputSpec) {
	*out = *in
	if in.ScriptConfigRef != nil {
		in, out := &in.ScriptConfigRef, &out.ScriptConfigRef
		*out = new(ScriptConfigRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StarlarkInputSpec.
func (in *StarlarkInputSpec) DeepCopy() *StarlarkInputSpec {
	if in == nil {
		return nil
	}
	out := new(StarlarkInputSpec)
	in.DeepCopyInto(out)
	return out
}
